### ISSUE TITLE
Job queue problems

### ISSUE THREAD

**Issue by Southparkfan** [Orain/ansible-playbook#535] opened 2015-02-26 22:37 UTC
For some reason no jobs are running on allthetropeswiki:

The amount of jobs per the API (https://allthetropes.orain.org/w/api.php?action=query&meta=siteinfo&siprop=statistics&format=jsonfm):
1297

The amount of jobs per the database:
\> select count(\*) from job;
stdClass Object
(
    [count(\*)] => 31881
)

Note - I thought jobs are deleted from the database when they are completed, if this is not the case, the fact that there are 31881 jobs in the database is not an issue then.

runJobs.php does nothing(?):
southparkfan@prod9 /srv/mediawiki/w/maintenance
 % php5 runJobs.php --wiki allthetropeswiki
southparkfan@prod9 /srv/mediawiki/w/maintenance

And not even with --nothrottle:
southparkfan@prod9 /srv/mediawiki/w/maintenance
 % php5 runJobs.php --wiki allthetropeswiki --nothrottle
southparkfan@prod9 /srv/mediawiki/w/maintenance

Tried things on prod8 and prod9 too - no luck.

**Comment by Arcane21** [comment] 2015-02-26 23:33
This is strange, though it could be what I like to call "ghost jobs".

Basically, jobs that fill up the database that have already been completed, but the records won't update for some reason. (it's usually safe to clean out the jobs database table manually if this is the case)

I just finished running a bot for the last few days on our "Trope" category, that could be the cause.

**Comment by Southparkfan** [comment] 2015-02-27 08:11
Yeah, I managed it to run I guess 10 htmlCache stuff jobs. Of course it is preferred to run the jobs instead of cleaning the job table - cleaning the job table would be a last solution for me.

**Comment by Southparkfan** [comment] 2015-02-27 18:18
@Arcane21 I guess I'll clean the table soon, but do you know if there are any bugs in Wikimedia Phabricator filed which are related to these job queue issues?

**Comment by Arcane21** [comment] 2015-02-27 18:40
None I'm aware.

**Comment by Southparkfan** [comment] 2015-02-27 22:51
It seems that ~1072 of the remaning jobs are "cirrusSearchLinksUpdate" jobs, which perhaps could better be deleted as we don't use CirrusSearch anymore.

**Comment by Arcane21** [comment] 2015-02-27 22:58
That can be safely deleted.

**Comment by Southparkfan** [comment] 2015-02-27 23:06
Done - now only 1593 (300 more than what the api says) rows left in the job table.

**Comment by addshore** [comment] 2015-03-02 16:35
Marking as closed for now per the above, if this does happen again please repoen and we can dig deeper

**Closed by addshore** 2015-03-02 16:35 UTC
Labels: wikiscripts
